// <auto-generated />
using System;
using Broker.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Broker.Migrations
{
    [DbContext(typeof(RopeContext))]
    partial class RopeContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.0-rtm-35687")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Broker.Models.Rope", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CaptureDate");

                    b.Property<int?>("ShipID1");

                    b.Property<string>("Tag");

                    b.HasKey("ID");

                    b.HasIndex("ShipID1");

                    b.ToTable("Rope");
                });

            modelBuilder.Entity("Broker.Models.Ship", b =>
                {
                    b.Property<int>("ShipID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.HasKey("ShipID");

                    b.ToTable("Ship");
                });

            modelBuilder.Entity("Broker.Models.Rope", b =>
                {
                    b.HasOne("Broker.Models.Ship", "ShipID")
                        .WithMany("Ropes")
                        .HasForeignKey("ShipID1");
                });
#pragma warning restore 612, 618
        }
    }
}
