// <auto-generated />
using System;
using BackendService.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BackendService.Migrations
{
    [DbContext(typeof(BackendServiceContext))]
    partial class BackendServiceContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.0-rtm-35687")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BackendService.Models.Image", b =>
                {
                    b.Property<int>("ImageID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CaptureDate");

                    b.Property<int>("Height");

                    b.Property<byte[]>("RawImage");

                    b.Property<int>("RopeID");

                    b.Property<int?>("ShipID");

                    b.Property<int>("Width");

                    b.HasKey("ImageID");

                    b.HasIndex("RopeID");

                    b.HasIndex("ShipID");

                    b.ToTable("Image");
                });

            modelBuilder.Entity("BackendService.Models.Rope", b =>
                {
                    b.Property<int>("RopeID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("AddedOn");

                    b.Property<double>("Probability");

                    b.Property<int>("ShipID");

                    b.Property<int>("Tag");

                    b.HasKey("RopeID");

                    b.HasIndex("ShipID");

                    b.ToTable("Rope");
                });

            modelBuilder.Entity("BackendService.Models.Ship", b =>
                {
                    b.Property<int>("ShipID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60);

                    b.HasKey("ShipID");

                    b.ToTable("Ship");
                });

            modelBuilder.Entity("BackendService.Models.Image", b =>
                {
                    b.HasOne("BackendService.Models.Rope", "Rope")
                        .WithMany("Images")
                        .HasForeignKey("RopeID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("BackendService.Models.Ship")
                        .WithMany("Images")
                        .HasForeignKey("ShipID");
                });

            modelBuilder.Entity("BackendService.Models.Rope", b =>
                {
                    b.HasOne("BackendService.Models.Ship", "Ship")
                        .WithMany("Ropes")
                        .HasForeignKey("ShipID")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
